swagger: '2.0'
info:
  title: Reporting API Documentation
  description: |
    <p><b>Some authentication.</b></p>
  version: '1.0.0'
schemes:
  - https
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
  - application/javascript #JSONP
  - application/xml
  - text/csv
  - text/tab-separated-values
  - text/html #wat
  - application/rss+xml
  #TODO: Add MIME for php and original formats. waaaaaaaaaaaaaaat?
paths:
  /:
    get:
      summary:
        Get analytics reports
      description: |
        <p>Returns a list of audiences which the profile belongs to. The only ID that can be used to identify the profile is <code>analytics_visitor_id</code>. In the response, you get only audiences IDs, names are not returned for security reasons.</p>
      parameters:
      - name: website_id
        in: query
        type: string
        format: uuid
        description: ID of the website.
        required: True
        example: '0fdd8cc2-93b1-428c-8373-97a452f5b10'
      - name: analytics_visitor_id
        in: path
        type: string
        format: string
        description: Piwik ID of the profile.
        required: True
        example: '3a0133748b3e524c'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: string
              example: '0fdd8cc2-93b1-428c-8373-97a452f5b10'
        400:
          description: Bad Request
        403:
          description: Forbidden
#definitions:
#  $ref: ./definitions/index.yaml
host: ppms.example.com
basePath: /
