swagger: '2.0'
info:
  title: Reporting API Documentation
  description: |
    **Authentication required.**
  version: '1.0.0'
schemes:
  - https
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
  - application/javascript #JSONP
  - application/xml
  - text/csv
  - text/tab-separated-values
  - text/html #wat
  - application/rss+xml
  #TODO: Add MIME for php and original formats. waaaaaaaaaaaaaaat?
paths:
  /:
    get:
      summary:
        Get analytics reports
      description: |
        Returns selected analytics report.
      parameters:
        - name: idSite
          in: query
          description: |
            App ID (previously Website ID). You can specify one or more IDs this way. It's also possible to generate
            report for all tracked applications using ``all`` value.
          required: true
          type: array
          collectionFormat: csv
          minItems: 1
          uniqueItems: true
          items:
            type: string
            format: uuid
            minimumLength: 36
            maximumLength: 36
          example: '0fdd8cc2-93b1-428c-8373-97a452f5b10c'
        - name: period
          in: query
          description: |
            Period of the report (length of reported time). It's used in conjunction with `date` parameter:

              - ``range`` period will use both values from `date` parameter to specify report boundries
              #TODO: Start of the week is not well defined. It may be Monday, Sunday or Saturday depending on locale.
              - other periods will select time period that insludes first value from `date` parameter (e.g. day, week,
                month or year).
          type: string
          required: true
          enum:
            - day
            - week
            - month
            - year
            - range
          example: 'month'
        - name: date
          in: query
          description: |
            Start date of the report. It may alco contain end date for `period`=``range``.

            TODO: Add all combinations of period/date
          required: true
          type: array
          collectionFormat: csv
          minItems: 1
          maxItems: 2
          items:
            type: string
            format: YYYY-MM-DD
          example: today
        - name: segment
          in: query
          #TODO: Check if example matches reality (set of segmentation rules instead of segment name defined in Analytics)
          #TODO: Confirm that "," is "OR" and ";" is "AND" operator
          description: |
            Custom segment filter (segmentation: https://help.piwik.pro/analytics/segmentation/). You can filter using
            multiple conditions using logic operations:

            - ``,`` - ``OR`` operator
            - ``;`` - ``AND`` operator
          type: string
          required: true
          example: referrerName==facebook.com,referrerName==twitter.com;country==US
        - name: format
          in: query
          #TODO: Confirm that "original" is the same as "php" with disabled serialization and deprecate it.
          description: |
            Determines output format:

            - ``xml`` - Extensible Markup Language
            - ``json`` - JavaScript Object Notation. Can be formatted as JSONP if ``jsoncallback`` parameter is set.
            - ``csv`` - Comma-Separated Values
            - ``tsv`` - Tab-Separated Values
            - ``html`` - Hypertext Markup Language
            - ``rss`` - Rich Site Summary
            - ``php`` - PHP: Hypertext Preprocessor. This format can be modified using ``serialize`` and
              ``prettyDisplay`` parameters.
            - ``original`` - Original PHP data structure.
          type: string
          enum:
            - xml
            - json
            - csv
            - tsv
            - html
            - rss
            - php
            - original
          required: true
          example: json
        - name: jsoncallback
          in: query
          description: (Option used by ``json`` format) Name of JSONP callback function.
          type: string
          example: displayReport
        - name: serialize
          in: query
          description: |
            (Option used by ``php`` format) Defines if output should be serialized (``0`` - no, use raw PHP data
            structure)
          type: integer
          minimum: 0
          maximum: 1
          default: 1
          example: 0
        - name: prettyDisplay
          in: query
          description: |
            (Option used by ``php`` format) Defines if output should use human-readable indentation (``1`` - yes).
          type: integer
          minimum: 0
          maximum: 1
          default: 0
          example: 1
        - name: language
          in: query
          description: |
            Language and locale of report data. You can check full list of options using
            ``LanguagesManager.getAvailableLanguages`` function.
          type: string
          enum:
            - am
            - ar
            - be
            - bg
            - bn
            - bs
            - ca
            - cs
            - cy
            - da
            - de
            - el
            - en
            - es
            - et
            - eu
            - fa
            - fi
            - fr
            - gl
            - he
            - hi
            - hr
            - hu
            - id
            - is
            - it
            - ja
            - ka
            - ko
            - lt
            - lv
            - nb
            - nl
            - nn
            - pl
            - pt-br
            - pt
            - ro
            - ru
            - sk
            - sl
            - sq
            - sr
            - sv
            - ta
            - te
            - th
            - tl
            - tr
            - uk
            - vi
            - zh-cn
            - zh-tw
          default: en
          example: uk
        #TODO: Explain linked tables (sub-tables) and list all available connected tables.
        - name: idSubtable
          in: query
          description: |
            Subtable ID. Some tables are linked in hierarchical order. It's used to specify to which parent entry is the
            subtable linked to (e.g. ``Referrers.getKeywordsFromSearchEngineId`` is a subtable of
            ``Referrers.getSearchEngines`` table and expects this parameter value to match value of ``idsubdatatable``
            attribute of one of the entries available in parent table).
          type: integer
          example: 3
        - name: expanded
          in: query
          #TODO: Description suggests that all subtables are included. Are there any multi-level linked tables and will it expand all levels if main parent table is called with this parameter?
          description: |
            Expands hierarchical results with subtables. If expanded parent table is requested, it's subtables are
            included in table results as a ``subtable`` attribute of each entry.
          minimum: 0
          maximum: 1
          default: 0
          example: 1
        - name: flat
          in: query
          #TODO: Format of this parameter is unclear. Add specifics:
          # - how is flattened data added (attribute name)?
          # - how is it aggregated?
          description: Flattens extended hierarchical tables with aggregared results.
          minimum: 0
          maximum: 1
          default: 0
          example: 1
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: string
              example: '0fdd8cc2-93b1-428c-8373-97a452f5b10'
        400:
          description: Bad Request
        403:
          description: Forbidden
#definitions:
#  $ref: ./definitions/index.yaml
host: ppms.example.com
basePath: /
